[2024-04-23T00:00:33.848+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_heart_data.split_dataset scheduled__2024-04-22T00:00:00+00:00 [queued]>
[2024-04-23T00:00:33.853+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_heart_data.split_dataset scheduled__2024-04-22T00:00:00+00:00 [queued]>
[2024-04-23T00:00:33.853+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-23T00:00:34.031+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): split_dataset> on 2024-04-22 00:00:00+00:00
[2024-04-23T00:00:34.035+0000] {standard_task_runner.py:60} INFO - Started process 44877 to run task
[2024-04-23T00:00:34.037+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_heart_data', 'split_dataset', 'scheduled__2024-04-22T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmpwajs4nkm']
[2024-04-23T00:00:34.038+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask split_dataset
[2024-04-23T00:00:34.520+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_heart_data.split_dataset scheduled__2024-04-22T00:00:00+00:00 [running]> on host d1bc6a951fa1
[2024-04-23T00:00:34.920+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Facundo Adrian Lucianna' AIRFLOW_CTX_DAG_ID='process_etl_heart_data' AIRFLOW_CTX_TASK_ID='split_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-04-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-22T00:00:00+00:00'
[2024-04-23T00:00:34.922+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv3up5wv1k --system-site-packages --python=python
[2024-04-23T00:00:34.929+0000] {process_utils.py:186} INFO - Output:
[2024-04-23T00:00:35.346+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 154ms
[2024-04-23T00:00:35.347+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv3up5wv1k, clear=False, no_vcs_ignore=False, global=True)
[2024-04-23T00:00:35.347+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-04-23T00:00:35.348+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-04-23T00:00:35.348+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-04-23T00:00:35.382+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv3up5wv1k/bin/pip install -r /tmp/venv3up5wv1k/requirements.txt
[2024-04-23T00:00:35.389+0000] {process_utils.py:186} INFO - Output:
[2024-04-23T00:00:36.677+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venv3up5wv1k/requirements.txt (line 1))
[2024-04-23T00:00:36.678+0000] {process_utils.py:190} INFO -   Using cached awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-04-23T00:00:36.680+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv3up5wv1k/requirements.txt (line 2)) (1.3.2)
[2024-04-23T00:00:36.712+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv3up5wv1k/requirements.txt (line 1)) (1.34.88)
[2024-04-23T00:00:36.712+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv3up5wv1k/requirements.txt (line 1)) (1.34.88)
[2024-04-23T00:00:36.713+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv3up5wv1k/requirements.txt (line 1)) (1.24.4)
[2024-04-23T00:00:36.714+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv3up5wv1k/requirements.txt (line 1)) (23.2)
[2024-04-23T00:00:36.715+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv3up5wv1k/requirements.txt (line 1)) (2.0.3)
[2024-04-23T00:00:36.716+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv3up5wv1k/requirements.txt (line 1)) (14.0.2)
[2024-04-23T00:00:36.716+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venv3up5wv1k/requirements.txt (line 1)) (4.9.0)
[2024-04-23T00:00:36.741+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy>=1.5.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv3up5wv1k/requirements.txt (line 2)) (1.10.1)
[2024-04-23T00:00:36.741+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv3up5wv1k/requirements.txt (line 2)) (1.4.0)
[2024-04-23T00:00:36.742+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv3up5wv1k/requirements.txt (line 2)) (3.4.0)
[2024-04-23T00:00:36.746+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venv3up5wv1k/requirements.txt (line 1)) (0.10.0)
[2024-04-23T00:00:36.747+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venv3up5wv1k/requirements.txt (line 1)) (0.10.1)
[2024-04-23T00:00:36.753+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venv3up5wv1k/requirements.txt (line 1)) (2.8.2)
[2024-04-23T00:00:36.754+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venv3up5wv1k/requirements.txt (line 1)) (1.26.18)
[2024-04-23T00:00:36.821+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venv3up5wv1k/requirements.txt (line 1)) (2023.3.post1)
[2024-04-23T00:00:36.822+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venv3up5wv1k/requirements.txt (line 1)) (2023.4)
[2024-04-23T00:00:36.844+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venv3up5wv1k/requirements.txt (line 1)) (1.16.0)
[2024-04-23T00:00:36.865+0000] {process_utils.py:190} INFO - Using cached awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-04-23T00:00:38.930+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2024-04-23T00:00:39.128+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0
[2024-04-23T00:00:39.522+0000] {process_utils.py:190} INFO - 
[2024-04-23T00:00:39.522+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.0
[2024-04-23T00:00:39.523+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-04-23T00:00:39.652+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv3up5wv1k/bin/python /tmp/venv-call0awq5zab/script.py /tmp/venv-call0awq5zab/script.in /tmp/venv-call0awq5zab/script.out /tmp/venv-call0awq5zab/string_args.txt /tmp/venv-call0awq5zab/termination.log
[2024-04-23T00:00:39.659+0000] {process_utils.py:186} INFO - Output:
[2024-04-23T00:00:41.198+0000] {process_utils.py:190} INFO - [[34m2024-04-23T00:00:41.197+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-04-23T00:00:41.308+0000] {process_utils.py:190} INFO - [[34m2024-04-23T00:00:41.308+0000[0m] {[34mconfigprovider.py:[0m957} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-04-23T00:00:41.367+0000] {process_utils.py:190} INFO - [[34m2024-04-23T00:00:41.367+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-04-23T00:00:41.402+0000] {process_utils.py:190} INFO - [[34m2024-04-23T00:00:41.402+0000[0m] {[34mconfigprovider.py:[0m957} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-04-23T00:00:41.616+0000] {process_utils.py:190} INFO - [[34m2024-04-23T00:00:41.616+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-04-23T00:00:41.649+0000] {process_utils.py:190} INFO - [[34m2024-04-23T00:00:41.649+0000[0m] {[34mconfigprovider.py:[0m957} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-04-23T00:00:42.006+0000] {process_utils.py:190} INFO - [[34m2024-04-23T00:00:42.006+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-04-23T00:00:42.040+0000] {process_utils.py:190} INFO - [[34m2024-04-23T00:00:42.040+0000[0m] {[34mconfigprovider.py:[0m957} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-04-23T00:00:42.209+0000] {process_utils.py:190} INFO - [[34m2024-04-23T00:00:42.209+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-04-23T00:00:42.372+0000] {process_utils.py:190} INFO - [[34m2024-04-23T00:00:42.372+0000[0m] {[34mconfigprovider.py:[0m957} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-04-23T00:00:46.973+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-04-23T00:00:46.982+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_heart_data, task_id=split_dataset, execution_date=20240422T000000, start_date=20240423T000033, end_date=20240423T000046
[2024-04-23T00:00:47.045+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-23T00:00:47.060+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
