[2024-04-24T00:00:01.463+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-04-24T00:00:01.468+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-04-24T00:00:01.468+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-24T00:00:01.475+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): obtain_original_data> on 2024-04-23 00:00:00+00:00
[2024-04-24T00:00:01.479+0000] {standard_task_runner.py:60} INFO - Started process 895 to run task
[2024-04-24T00:00:01.481+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_mnist_784_data', 'obtain_original_data', 'scheduled__2024-04-23T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/etl_process_new.py', '--cfg-path', '/tmp/tmp65dww4dl']
[2024-04-24T00:00:01.482+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask obtain_original_data
[2024-04-24T00:00:01.509+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-23T00:00:00+00:00 [running]> on host 8145552d2c53
[2024-04-24T00:00:01.554+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Carlos Rodriguez' AIRFLOW_CTX_DAG_ID='process_etl_mnist_784_data' AIRFLOW_CTX_TASK_ID='obtain_original_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-23T00:00:00+00:00'
[2024-04-24T00:00:01.555+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvzd_llhh9 --system-site-packages --python=python
[2024-04-24T00:00:01.562+0000] {process_utils.py:186} INFO - Output:
[2024-04-24T00:00:02.099+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 278ms
[2024-04-24T00:00:02.100+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvzd_llhh9, clear=False, no_vcs_ignore=False, global=True)
[2024-04-24T00:00:02.100+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-04-24T00:00:02.101+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.0, setuptools==69.2.0, wheel==0.43.0
[2024-04-24T00:00:02.101+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-04-24T00:00:02.122+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvzd_llhh9/bin/pip install -r /tmp/venvzd_llhh9/requirements.txt
[2024-04-24T00:00:02.128+0000] {process_utils.py:186} INFO - Output:
[2024-04-24T00:00:03.039+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venvzd_llhh9/requirements.txt (line 1))
[2024-04-24T00:00:03.041+0000] {process_utils.py:190} INFO -   Using cached awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-04-24T00:00:03.073+0000] {process_utils.py:190} INFO - Collecting ucimlrepo==0.0.3 (from -r /tmp/venvzd_llhh9/requirements.txt (line 2))
[2024-04-24T00:00:03.074+0000] {process_utils.py:190} INFO -   Using cached ucimlrepo-0.0.3-py3-none-any.whl.metadata (5.2 kB)
[2024-04-24T00:00:03.104+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvzd_llhh9/requirements.txt (line 1)) (1.34.88)
[2024-04-24T00:00:03.105+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvzd_llhh9/requirements.txt (line 1)) (1.34.88)
[2024-04-24T00:00:03.105+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvzd_llhh9/requirements.txt (line 1)) (1.24.4)
[2024-04-24T00:00:03.106+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvzd_llhh9/requirements.txt (line 1)) (23.2)
[2024-04-24T00:00:03.107+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvzd_llhh9/requirements.txt (line 1)) (2.0.3)
[2024-04-24T00:00:03.107+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvzd_llhh9/requirements.txt (line 1)) (14.0.2)
[2024-04-24T00:00:03.108+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvzd_llhh9/requirements.txt (line 1)) (4.9.0)
[2024-04-24T00:00:03.112+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvzd_llhh9/requirements.txt (line 1)) (0.10.0)
[2024-04-24T00:00:03.113+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvzd_llhh9/requirements.txt (line 1)) (0.10.1)
[2024-04-24T00:00:03.117+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvzd_llhh9/requirements.txt (line 1)) (2.8.2)
[2024-04-24T00:00:03.118+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvzd_llhh9/requirements.txt (line 1)) (1.26.18)
[2024-04-24T00:00:03.175+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvzd_llhh9/requirements.txt (line 1)) (2023.3.post1)
[2024-04-24T00:00:03.175+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvzd_llhh9/requirements.txt (line 1)) (2023.4)
[2024-04-24T00:00:03.181+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvzd_llhh9/requirements.txt (line 1)) (1.16.0)
[2024-04-24T00:00:03.202+0000] {process_utils.py:190} INFO - Using cached awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-04-24T00:00:03.203+0000] {process_utils.py:190} INFO - Using cached ucimlrepo-0.0.3-py3-none-any.whl (7.0 kB)
[2024-04-24T00:00:05.137+0000] {process_utils.py:190} INFO - Installing collected packages: ucimlrepo, awswrangler
[2024-04-24T00:00:05.295+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0 ucimlrepo-0.0.3
[2024-04-24T00:00:05.513+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvzd_llhh9/bin/python /tmp/venv-callp0e0lqnq/script.py /tmp/venv-callp0e0lqnq/script.in /tmp/venv-callp0e0lqnq/script.out /tmp/venv-callp0e0lqnq/string_args.txt /tmp/venv-callp0e0lqnq/termination.log
[2024-04-24T00:00:05.521+0000] {process_utils.py:186} INFO - Output:
[2024-04-24T00:00:06.567+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-04-24T00:00:06.568+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callp0e0lqnq/script.py", line 57, in <module>
[2024-04-24T00:00:06.568+0000] {process_utils.py:190} INFO -     res = get_data(*arg_dict["args"], **arg_dict["kwargs"])
[2024-04-24T00:00:06.569+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callp0e0lqnq/script.py", line 41, in get_data
[2024-04-24T00:00:06.569+0000] {process_utils.py:190} INFO -     mnist = fetch_openml('mnist_784', as_frame = False)
[2024-04-24T00:00:06.569+0000] {process_utils.py:190} INFO - NameError: name 'fetch_openml' is not defined
[2024-04-24T00:00:06.758+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
name 'fetch_openml' is not defined
[2024-04-24T00:00:06.760+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=process_etl_mnist_784_data, task_id=obtain_original_data, execution_date=20240423T000000, start_date=20240424T000001, end_date=20240424T000006
[2024-04-24T00:00:06.768+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task obtain_original_data (Process returned non-zero exit status 1.
name 'fetch_openml' is not defined; 895)
[2024-04-24T00:00:06.813+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-24T00:00:06.826+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-24T10:41:47.651+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-04-24T10:41:47.656+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-04-24T10:41:47.657+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-24T10:41:47.665+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): obtain_original_data> on 2024-04-23 00:00:00+00:00
[2024-04-24T10:41:47.670+0000] {standard_task_runner.py:60} INFO - Started process 1298 to run task
[2024-04-24T10:41:47.672+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_mnist_784_data', 'obtain_original_data', 'scheduled__2024-04-23T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_process_new.py', '--cfg-path', '/tmp/tmp3z_9aa4e']
[2024-04-24T10:41:47.673+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask obtain_original_data
[2024-04-24T10:41:47.708+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-23T00:00:00+00:00 [running]> on host a2eae1f987eb
[2024-04-24T10:41:47.760+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Carlos Rodriguez' AIRFLOW_CTX_DAG_ID='process_etl_mnist_784_data' AIRFLOW_CTX_TASK_ID='obtain_original_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-23T00:00:00+00:00'
[2024-04-24T10:41:47.761+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvjy6q5yj2 --system-site-packages --python=python
[2024-04-24T10:41:47.771+0000] {process_utils.py:186} INFO - Output:
[2024-04-24T10:41:48.415+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 325ms
[2024-04-24T10:41:48.415+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvjy6q5yj2, clear=False, no_vcs_ignore=False, global=True)
[2024-04-24T10:41:48.416+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-04-24T10:41:48.416+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-04-24T10:41:48.417+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-04-24T10:41:48.484+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvjy6q5yj2/bin/pip install -r /tmp/venvjy6q5yj2/requirements.txt
[2024-04-24T10:41:48.500+0000] {process_utils.py:186} INFO - Output:
[2024-04-24T10:41:49.878+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venvjy6q5yj2/requirements.txt (line 1))
[2024-04-24T10:41:50.020+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-04-24T10:41:50.068+0000] {process_utils.py:190} INFO - Collecting ucimlrepo==0.0.3 (from -r /tmp/venvjy6q5yj2/requirements.txt (line 2))
[2024-04-24T10:41:50.100+0000] {process_utils.py:190} INFO -   Downloading ucimlrepo-0.0.3-py3-none-any.whl.metadata (5.2 kB)
[2024-04-24T10:41:50.166+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvjy6q5yj2/requirements.txt (line 1)) (1.34.90)
[2024-04-24T10:41:50.168+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvjy6q5yj2/requirements.txt (line 1)) (1.34.90)
[2024-04-24T10:41:50.170+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvjy6q5yj2/requirements.txt (line 1)) (1.24.4)
[2024-04-24T10:41:50.170+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvjy6q5yj2/requirements.txt (line 1)) (23.2)
[2024-04-24T10:41:50.172+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvjy6q5yj2/requirements.txt (line 1)) (2.0.3)
[2024-04-24T10:41:50.173+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvjy6q5yj2/requirements.txt (line 1)) (14.0.2)
[2024-04-24T10:41:50.173+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvjy6q5yj2/requirements.txt (line 1)) (4.9.0)
[2024-04-24T10:41:50.182+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvjy6q5yj2/requirements.txt (line 1)) (0.10.0)
[2024-04-24T10:41:50.182+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvjy6q5yj2/requirements.txt (line 1)) (0.10.1)
[2024-04-24T10:41:50.190+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvjy6q5yj2/requirements.txt (line 1)) (2.8.2)
[2024-04-24T10:41:50.191+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvjy6q5yj2/requirements.txt (line 1)) (1.26.18)
[2024-04-24T10:41:50.268+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvjy6q5yj2/requirements.txt (line 1)) (2023.3.post1)
[2024-04-24T10:41:50.269+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvjy6q5yj2/requirements.txt (line 1)) (2023.4)
[2024-04-24T10:41:50.279+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvjy6q5yj2/requirements.txt (line 1)) (1.16.0)
[2024-04-24T10:41:50.335+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-04-24T10:41:50.419+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.8/403.8 kB 4.9 MB/s eta 0:00:00
[2024-04-24T10:41:50.447+0000] {process_utils.py:190} INFO - Downloading ucimlrepo-0.0.3-py3-none-any.whl (7.0 kB)
[2024-04-24T10:41:52.901+0000] {process_utils.py:190} INFO - Installing collected packages: ucimlrepo, awswrangler
[2024-04-24T10:41:53.102+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0 ucimlrepo-0.0.3
[2024-04-24T10:41:53.245+0000] {process_utils.py:190} INFO - 
[2024-04-24T10:41:53.246+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.0
[2024-04-24T10:41:53.246+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-04-24T10:41:53.496+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvjy6q5yj2/bin/python /tmp/venv-callkq_5nlfd/script.py /tmp/venv-callkq_5nlfd/script.in /tmp/venv-callkq_5nlfd/script.out /tmp/venv-callkq_5nlfd/string_args.txt /tmp/venv-callkq_5nlfd/termination.log
[2024-04-24T10:41:53.505+0000] {process_utils.py:186} INFO - Output:
[2024-04-24T10:41:55.103+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-04-24T10:41:55.103+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callkq_5nlfd/script.py", line 57, in <module>
[2024-04-24T10:41:55.103+0000] {process_utils.py:190} INFO -     res = get_data(*arg_dict["args"], **arg_dict["kwargs"])
[2024-04-24T10:41:55.104+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callkq_5nlfd/script.py", line 41, in get_data
[2024-04-24T10:41:55.104+0000] {process_utils.py:190} INFO -     mnist = fetch_openml('mnist_784', as_frame = False)
[2024-04-24T10:41:55.104+0000] {process_utils.py:190} INFO - NameError: name 'fetch_openml' is not defined
[2024-04-24T10:41:55.456+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
name 'fetch_openml' is not defined
[2024-04-24T10:41:55.458+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=process_etl_mnist_784_data, task_id=obtain_original_data, execution_date=20240423T000000, start_date=20240424T104147, end_date=20240424T104155
[2024-04-24T10:41:55.467+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task obtain_original_data (Process returned non-zero exit status 1.
name 'fetch_openml' is not defined; 1298)
[2024-04-24T10:41:55.502+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-24T10:41:55.519+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-24T23:43:33.287+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-04-24T23:43:33.293+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-04-24T23:43:33.293+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-24T23:43:33.302+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): obtain_original_data> on 2024-04-23 00:00:00+00:00
[2024-04-24T23:43:33.306+0000] {standard_task_runner.py:60} INFO - Started process 13043 to run task
[2024-04-24T23:43:33.309+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_mnist_784_data', 'obtain_original_data', 'scheduled__2024-04-23T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmpa_wop_4c']
[2024-04-24T23:43:33.310+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask obtain_original_data
[2024-04-24T23:43:33.345+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_mnist_784_data.obtain_original_data scheduled__2024-04-23T00:00:00+00:00 [running]> on host 6bdddfadcc67
[2024-04-24T23:43:33.399+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Carlos Rodriguez' AIRFLOW_CTX_DAG_ID='process_etl_mnist_784_data' AIRFLOW_CTX_TASK_ID='obtain_original_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-23T00:00:00+00:00'
[2024-04-24T23:43:33.401+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvk6vaxal5 --system-site-packages --python=python
[2024-04-24T23:43:33.408+0000] {process_utils.py:186} INFO - Output:
[2024-04-24T23:43:34.068+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 351ms
[2024-04-24T23:43:34.069+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvk6vaxal5, clear=False, no_vcs_ignore=False, global=True)
[2024-04-24T23:43:34.069+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-04-24T23:43:34.070+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-04-24T23:43:34.071+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-04-24T23:43:34.131+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvk6vaxal5/bin/pip install -r /tmp/venvk6vaxal5/requirements.txt
[2024-04-24T23:43:34.141+0000] {process_utils.py:186} INFO - Output:
[2024-04-24T23:43:35.321+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venvk6vaxal5/requirements.txt (line 1))
[2024-04-24T23:43:35.432+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-04-24T23:43:35.619+0000] {process_utils.py:190} INFO - Collecting ucimlrepo==0.0.3 (from -r /tmp/venvk6vaxal5/requirements.txt (line 2))
[2024-04-24T23:43:35.643+0000] {process_utils.py:190} INFO -   Downloading ucimlrepo-0.0.3-py3-none-any.whl.metadata (5.2 kB)
[2024-04-24T23:43:35.695+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvk6vaxal5/requirements.txt (line 1)) (1.34.88)
[2024-04-24T23:43:35.696+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvk6vaxal5/requirements.txt (line 1)) (1.34.88)
[2024-04-24T23:43:35.697+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvk6vaxal5/requirements.txt (line 1)) (1.24.4)
[2024-04-24T23:43:35.697+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvk6vaxal5/requirements.txt (line 1)) (23.2)
[2024-04-24T23:43:35.698+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvk6vaxal5/requirements.txt (line 1)) (2.0.3)
[2024-04-24T23:43:35.699+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvk6vaxal5/requirements.txt (line 1)) (14.0.2)
[2024-04-24T23:43:35.699+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvk6vaxal5/requirements.txt (line 1)) (4.9.0)
[2024-04-24T23:43:35.704+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvk6vaxal5/requirements.txt (line 1)) (0.10.0)
[2024-04-24T23:43:35.705+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvk6vaxal5/requirements.txt (line 1)) (0.10.1)
[2024-04-24T23:43:35.711+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvk6vaxal5/requirements.txt (line 1)) (2.8.2)
[2024-04-24T23:43:35.712+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvk6vaxal5/requirements.txt (line 1)) (1.26.18)
[2024-04-24T23:43:35.792+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvk6vaxal5/requirements.txt (line 1)) (2023.3.post1)
[2024-04-24T23:43:35.793+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvk6vaxal5/requirements.txt (line 1)) (2023.4)
[2024-04-24T23:43:35.802+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvk6vaxal5/requirements.txt (line 1)) (1.16.0)
[2024-04-24T23:43:35.856+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-04-24T23:43:35.952+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.8/403.8 kB 4.3 MB/s eta 0:00:00
[2024-04-24T23:43:35.977+0000] {process_utils.py:190} INFO - Downloading ucimlrepo-0.0.3-py3-none-any.whl (7.0 kB)
[2024-04-24T23:43:38.297+0000] {process_utils.py:190} INFO - Installing collected packages: ucimlrepo, awswrangler
[2024-04-24T23:43:38.470+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0 ucimlrepo-0.0.3
[2024-04-24T23:43:38.600+0000] {process_utils.py:190} INFO - 
[2024-04-24T23:43:38.601+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.0
[2024-04-24T23:43:38.601+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-04-24T23:43:38.764+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvk6vaxal5/bin/python /tmp/venv-calljbiakefe/script.py /tmp/venv-calljbiakefe/script.in /tmp/venv-calljbiakefe/script.out /tmp/venv-calljbiakefe/string_args.txt /tmp/venv-calljbiakefe/termination.log
[2024-04-24T23:43:38.770+0000] {process_utils.py:186} INFO - Output:
[2024-04-24T23:43:43.627+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/sklearn/datasets/_openml.py:1022 FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
[2024-04-24T23:44:13.895+0000] {process_utils.py:190} INFO - [[34m2024-04-24T23:44:13.895+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-04-24T23:44:14.058+0000] {process_utils.py:190} INFO - [[34m2024-04-24T23:44:14.057+0000[0m] {[34mconfigprovider.py:[0m957} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-04-24T23:44:43.941+0000] {process_utils.py:190} INFO - [[34m2024-04-24T23:44:43.940+0000[0m] {[34mconnectionpool.py:[0m323} WARNING[0m - Connection pool is full, discarding connection: s3. Connection pool size: 10[0m
[2024-04-24T23:44:44.317+0000] {process_utils.py:190} INFO - [[34m2024-04-24T23:44:44.310+0000[0m] {[34mconnectionpool.py:[0m323} WARNING[0m - Connection pool is full, discarding connection: s3. Connection pool size: 10[0m
[2024-04-24T23:44:49.087+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-04-24T23:44:49.095+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_mnist_784_data, task_id=obtain_original_data, execution_date=20240423T000000, start_date=20240424T234333, end_date=20240424T234449
[2024-04-24T23:44:49.107+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-24T23:44:49.118+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
